### ISSUE TITLE
I do not see any affect with the theme

### ISSUE THREAD

**Issue by gerroon** [go-gitea/gitea-darkmode#1]
Hi

I followed your guid in the read me and I see no change whatsoever.

.```

├── custom
│   └── conf
│       └── app.ini
├── data
│   ├── avatars
│   │   └── e7f9daf57deb22a0dfd2ee9afc2788de
│   ├── gitea.db
│   ├── indexers
│   │   └── issues.bleve
│   │       ├── index_meta.json
│   │       └── store
│   ├── lfs
│   └── sessions
│       └── f
│           └── b
│               └── fb4ab8f1d97ec902
├── del
├── gitea-master-linux-amd64
├── images
│   ├── 1.png
│   ├── 2.png
│   ├── 3.png
│   ├── 4.png
│   └── 5.png
├── log
│   ├── gitea.log
│   ├── hooks
│   │   ├── post-receive.log
│   │   ├── pre-receive.log
│   │   └── update.log
│   ├── http.log
│   ├── serv.log
│   └── xorm.log
├── public
│   └── styles.css
├── templates
      └── custom
            └── header.tmpl

I changed the permissions properly as well.

```

It is not formatting templates properly above

```
templates
--custom
----header.tmpl
```

**Comment by Aztorius** [comment]
Your need to move templates/ and public/ into custom/

**Comment by gerroon** [comment]
Thanks, it works however you might want to amke that clear in the front page. 

"Put public/styles.css into the public/ directory of your gitea installation (you may need to create it), and place templates/custom/header.tmpl into the templates/custom/ directory of your gitea installation."

This just sounds like I put the files in the root of gitea folder (/opt/gitea for me). You might want to make that clear to the users.

**Comment by oz10h** [comment]
@Aztorius  Thank you soo much!

Why are must people complicate things.

Your description of the task is on point.

**Comment by vszakats** [comment]
For anybody trying to make this work on macOS via the `brew tap go-gitea/gitea` [installation method](https://docs.gitea.io/en-us/install-from-package/), the variable `GITEA_CUSTOM` must be set to the `custom` directory.

For a LaunchAgent `.plist`, it can be done like this:
```xml
    <key>EnvironmentVariables</key>
    <dict>
      <key>GITEA_CUSTOM</key>
      <string>(gitea_data_root_directory)/custom</string>
    </dict>
```
