### ISSUE TITLE
Tables are unreadable

### ISSUE THREAD

**Issue by tastytea** [go-gitea/gitea-darkmode#3]
![screenshot_2018-06-04t01 23 57](https://user-images.githubusercontent.com/3681516/40892338-47da32b6-6785-11e8-9610-0f6fd6c0aa3d.png)

Looks like the foreground-color is missing.

Gitea version: 1.4.1
Theme version: master branch

**Comment by jhabdas** [comment]
Holy lord lol I just noticed this on a very large table. Man, I wish this was fixed before this was merged into the main repo giving there are 800 open issues 0_o
