### ISSUE TITLE
2 different background-colors in code segments

### ISSUE THREAD

**Issue by tastytea** [go-gitea/gitea-darkmode#4]
![screenshot_2018-06-04t01 27 20](https://user-images.githubusercontent.com/3681516/40892367-b7b028f2-6785-11e8-8d2d-2f01e0e9e9a7.png)

This happens within code-segments in Markdown files. Sourcecode files are okay.

Gitea version: 1.4.1
Theme version: master branch

**Comment by jhabdas** [comment]
Should this be moved to the main repo now?
