### ISSUE TITLE
Theme not working under docker version

### ISSUE THREAD

**Issue by PeterBee97** [go-gitea/gitea-darkmode#5]
I don't really understand where to put the files in docker version of gitea. I tried to put it under / /etc/ but no luck. Could you tell me if I'm able to use this theme in docker version and what should I do? Please, I'm huuuuuuuuuungry for the dark theme~

**Comment by techknowlogick** [comment]
Here is my file structure for including the dark theme in docker: (the folder at the top is /data/gitea)
![screen shot 2018-06-04 at 2 15 06 pm](https://user-images.githubusercontent.com/164197/41218637-c34ee08c-6d29-11e8-99a9-b0867882e9ce.png)

**Comment by PeterBee97** [comment]
Thanks a lot, dude! It works!
