### ISSUE TITLE
Wiki editor-toolbar icons invisible

### ISSUE THREAD

**Issue by Reiiii** [go-gitea/gitea-darkmode#6]
The icons on the editor-toolbar when editing a wiki-page are invisible.

![bildschirmfoto von 2018-06-06 15-38-52](https://user-images.githubusercontent.com/17003689/41041646-e9f52030-699f-11e8-97a5-3f8b2a0ef866.png)

Adding the following to styles.css should fix it:
`
.editor-toolbar a {
  color: #87ab63 !important;
}`

Gitea Version: 1.4.1

**Comment by techknowlogick** [comment]
Can you create a PR for this?
