### ISSUE TITLE
which folders do you mean

### ISSUE THREAD

**Issue by monouser7dig** [go-gitea/gitea-darkmode#9]
the readme says:
>  and place templates/custom/header.tmpl into the templates/custom/

I run gitea using docker and have a gitea/custom folder (next to it is git/)

do you mean I should place the files in the respective gitea/custom/public and gitea/custom/templates/custom folder?

this does not seem to work for me

**Comment by techknowlogick** [comment]
Please see #5

**Comment by monouser7dig** [comment]
thanks for the quick response, it works ! 

I was confused because I looked at the gitea main website where customizing gitea was explained and I could not quite fit the descriptions together.
